In [7]:
import numpy as np

def rotation_matrix_x(angle_degrees):
    angle_radians = angle_degrees * (np.pi / 180)
    return np.array([[1, 0, 0],
                     [0, np.cos(angle_radians), -np.sin(angle_radians)],
                     [0, np.sin(angle_radians), np.cos(angle_radians)]])

# Function to create a rotation matrix for rotation around the Y-axis
def rotation_matrix_y(angle_degrees):
    angle_radians = angle_degrees * (np.pi / 180)
    return np.array([[np.cos(angle_radians), 0, np.sin(angle_radians)],
                     [0, 1, 0],
                     [-np.sin(angle_radians), 0, np.cos(angle_radians)]])

# Function to create a rotation matrix for rotation around the Z-axis
def rotation_matrix_z(angle_degrees):
    angle_radians = angle_degrees * (np.pi / 180)
    return np.array([[np.cos(angle_radians), -np.sin(angle_radians), 0],
                     [np.sin(angle_radians), np.cos(angle_radians), 0],
                     [0, 0, 1]])

# Function to apply rotation to a set of 3D points
def rotate_points(points, angle_degrees, axis='x'):
    if axis not in ['x', 'y', 'z']:
        raise ValueError("Axis must be 'x', 'y', or 'z'.")
    
    rotation_matrix = {
        'x': rotation_matrix_x(angle_degrees),
        'y': rotation_matrix_y(angle_degrees),
        'z': rotation_matrix_z(angle_degrees)
    }[axis]
    
    return np.transpose(np.dot(rotation_matrix, np.transpose(points))) # Apply rotation and return new points

# Example usage:
points = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

# Rotate 45 degrees around the Z-axis
rotated_points = rotate_points(points, 45, 'z')
print(rotated_points)


[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [8]:
def cross_product(a, b):
    if len(a) != 3 or len(b) != 3:
        raise ValueError("Both vectors must have three elements.")
    
    return [a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]]

def angle_difference(vec1, target):
    dot_product = np.dot(vec1, target)
    mag_vec1 = np.linalg.norm(vec1)
    mag_target = np.linalg.norm(target)
    
    cos_angle = dot_product / (mag_vec1 * mag_target)
    cos_angle = max(-1, min(1, cos_angle))
    
    angle_radians = np.arccos(cos_angle)
    
    return angle_radians

def rotate_vector_to_align(vec1, target):
    # Calculate the cross product (axis of rotation)
    rotation_axis = cross_product(vec1, target)
    
    # Calculate the angle between the vectors in radians
    angle_diff_rad = angle_difference(vec1, target) * (np.pi / 180)
    
    # Normalize the rotation axis
    rotation_axis = rotation_axis / np.sqrt(np.sum(np.square(rotation_axis)))
    
    # Rodrigues' rotation formula components
    K = np.array([[0, -rotation_axis[2], rotation_axis[1]],
                  [rotation_axis[2], 0, -rotation_axis[0]],
                  [-rotation_axis[1], rotation_axis[0], 0]])
    I = np.eye(3)
    R = I + np.sin(angle_diff_rad) * K + (1 - np.cos(angle_diff_rad)) * np.dot(K, K)
    
    # Rotate vec1
    rotated_vec1 = np.dot(R, vec1)
    
    # Return the rotated vector
    return rotated_vec1


In [9]:
vec1 = [0, 1, 0]
target = [0, 1, 1]

rotated_vec1 = rotate_vector_to_align(vec1, target)
rotated_vec2 = rotate_vector_to_align(rotated_vec1, target)
rotated_vec3 = rotate_vector_to_align(rotated_vec2, target)

print("Rotated Vector:")
print(rotated_vec1)
print(rotated_vec2)
print(rotated_vec3)


Rotated Vector:
[0.         0.99990605 0.01370735]
[0.         0.99963075 0.02717298]
[0.         0.99918364 0.04039879]
